# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtoApiResult.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProtoApiResult.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14ProtoApiResult.proto\"\xb2\x01\n\x0eProtoApiResult\x12)\n\x08messages\x18\x01 \x03(\x0b\x32\x17.ProtoApiResult.message\x12\x0e\n\x06\x63ursor\x18\x02 \x01(\t\x12\x16\n\x0e\x66\x65tch_interval\x18\x03 \x01(\x05\x12\x0b\n\x03now\x18\x04 \x01(\x04\x12\x14\n\x0cinternal_ext\x18\x05 \x01(\t\x1a*\n\x07message\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c'
)




_PROTOAPIRESULT_MESSAGE = _descriptor.Descriptor(
  name='message',
  full_name='ProtoApiResult.message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='method', full_name='ProtoApiResult.message.method', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='payload', full_name='ProtoApiResult.message.payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=203,
)

_PROTOAPIRESULT = _descriptor.Descriptor(
  name='ProtoApiResult',
  full_name='ProtoApiResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='messages', full_name='ProtoApiResult.messages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cursor', full_name='ProtoApiResult.cursor', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fetch_interval', full_name='ProtoApiResult.fetch_interval', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='now', full_name='ProtoApiResult.now', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='internal_ext', full_name='ProtoApiResult.internal_ext', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_PROTOAPIRESULT_MESSAGE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=203,
)

_PROTOAPIRESULT_MESSAGE.containing_type = _PROTOAPIRESULT
_PROTOAPIRESULT.fields_by_name['messages'].message_type = _PROTOAPIRESULT_MESSAGE
DESCRIPTOR.message_types_by_name['ProtoApiResult'] = _PROTOAPIRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProtoApiResult = _reflection.GeneratedProtocolMessageType('ProtoApiResult', (_message.Message,), {

  'message' : _reflection.GeneratedProtocolMessageType('message', (_message.Message,), {
    'DESCRIPTOR' : _PROTOAPIRESULT_MESSAGE,
    '__module__' : 'ProtoApiResult_pb2'
    # @@protoc_insertion_point(class_scope:ProtoApiResult.message)
    })
  ,
  'DESCRIPTOR' : _PROTOAPIRESULT,
  '__module__' : 'ProtoApiResult_pb2'
  # @@protoc_insertion_point(class_scope:ProtoApiResult)
  })
_sym_db.RegisterMessage(ProtoApiResult)
_sym_db.RegisterMessage(ProtoApiResult.message)


# @@protoc_insertion_point(module_scope)
