// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoApiResult.proto

public final class ProtoApiResultOuterClass {
  private ProtoApiResultOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProtoApiResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ProtoApiResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ProtoApiResult.message messages = 1;</code>
     */
    java.util.List<ProtoApiResultOuterClass.ProtoApiResult.message> 
        getMessagesList();
    /**
     * <code>repeated .ProtoApiResult.message messages = 1;</code>
     */
    ProtoApiResultOuterClass.ProtoApiResult.message getMessages(int index);
    /**
     * <code>repeated .ProtoApiResult.message messages = 1;</code>
     */
    int getMessagesCount();
    /**
     * <code>repeated .ProtoApiResult.message messages = 1;</code>
     */
    java.util.List<? extends ProtoApiResultOuterClass.ProtoApiResult.messageOrBuilder> 
        getMessagesOrBuilderList();
    /**
     * <code>repeated .ProtoApiResult.message messages = 1;</code>
     */
    ProtoApiResultOuterClass.ProtoApiResult.messageOrBuilder getMessagesOrBuilder(
        int index);

    /**
     * <code>optional string cursor = 2;</code>
     * @return Whether the cursor field is set.
     */
    boolean hasCursor();
    /**
     * <code>optional string cursor = 2;</code>
     * @return The cursor.
     */
    java.lang.String getCursor();
    /**
     * <code>optional string cursor = 2;</code>
     * @return The bytes for cursor.
     */
    com.google.protobuf.ByteString
        getCursorBytes();

    /**
     * <code>optional int32 fetch_interval = 3;</code>
     * @return Whether the fetchInterval field is set.
     */
    boolean hasFetchInterval();
    /**
     * <code>optional int32 fetch_interval = 3;</code>
     * @return The fetchInterval.
     */
    int getFetchInterval();

    /**
     * <code>optional uint64 now = 4;</code>
     * @return Whether the now field is set.
     */
    boolean hasNow();
    /**
     * <code>optional uint64 now = 4;</code>
     * @return The now.
     */
    long getNow();

    /**
     * <code>optional string internal_ext = 5;</code>
     * @return Whether the internalExt field is set.
     */
    boolean hasInternalExt();
    /**
     * <code>optional string internal_ext = 5;</code>
     * @return The internalExt.
     */
    java.lang.String getInternalExt();
    /**
     * <code>optional string internal_ext = 5;</code>
     * @return The bytes for internalExt.
     */
    com.google.protobuf.ByteString
        getInternalExtBytes();
  }
  /**
   * Protobuf type {@code ProtoApiResult}
   */
  public static final class ProtoApiResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ProtoApiResult)
      ProtoApiResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ProtoApiResult.newBuilder() to construct.
    private ProtoApiResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProtoApiResult() {
      messages_ = java.util.Collections.emptyList();
      cursor_ = "";
      internalExt_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ProtoApiResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoApiResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                messages_ = new java.util.ArrayList<ProtoApiResultOuterClass.ProtoApiResult.message>();
                mutable_bitField0_ |= 0x00000001;
              }
              messages_.add(
                  input.readMessage(ProtoApiResultOuterClass.ProtoApiResult.message.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              cursor_ = bs;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000002;
              fetchInterval_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              now_ = input.readUInt64();
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              internalExt_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          messages_ = java.util.Collections.unmodifiableList(messages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProtoApiResultOuterClass.internal_static_ProtoApiResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProtoApiResultOuterClass.internal_static_ProtoApiResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProtoApiResultOuterClass.ProtoApiResult.class, ProtoApiResultOuterClass.ProtoApiResult.Builder.class);
    }

    public interface messageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ProtoApiResult.message)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string method = 1;</code>
       * @return Whether the method field is set.
       */
      boolean hasMethod();
      /**
       * <code>optional string method = 1;</code>
       * @return The method.
       */
      java.lang.String getMethod();
      /**
       * <code>optional string method = 1;</code>
       * @return The bytes for method.
       */
      com.google.protobuf.ByteString
          getMethodBytes();

      /**
       * <code>optional bytes payload = 2;</code>
       * @return Whether the payload field is set.
       */
      boolean hasPayload();
      /**
       * <code>optional bytes payload = 2;</code>
       * @return The payload.
       */
      com.google.protobuf.ByteString getPayload();
    }
    /**
     * Protobuf type {@code ProtoApiResult.message}
     */
    public static final class message extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:ProtoApiResult.message)
        messageOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use message.newBuilder() to construct.
      private message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private message() {
        method_ = "";
        payload_ = com.google.protobuf.ByteString.EMPTY;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new message();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private message(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                method_ = bs;
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                payload_ = input.readBytes();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoApiResultOuterClass.internal_static_ProtoApiResult_message_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoApiResultOuterClass.internal_static_ProtoApiResult_message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoApiResultOuterClass.ProtoApiResult.message.class, ProtoApiResultOuterClass.ProtoApiResult.message.Builder.class);
      }

      private int bitField0_;
      public static final int METHOD_FIELD_NUMBER = 1;
      private volatile java.lang.Object method_;
      /**
       * <code>optional string method = 1;</code>
       * @return Whether the method field is set.
       */
      @java.lang.Override
      public boolean hasMethod() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string method = 1;</code>
       * @return The method.
       */
      @java.lang.Override
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            method_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string method = 1;</code>
       * @return The bytes for method.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PAYLOAD_FIELD_NUMBER = 2;
      private com.google.protobuf.ByteString payload_;
      /**
       * <code>optional bytes payload = 2;</code>
       * @return Whether the payload field is set.
       */
      @java.lang.Override
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bytes payload = 2;</code>
       * @return The payload.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, method_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeBytes(2, payload_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, method_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, payload_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof ProtoApiResultOuterClass.ProtoApiResult.message)) {
          return super.equals(obj);
        }
        ProtoApiResultOuterClass.ProtoApiResult.message other = (ProtoApiResultOuterClass.ProtoApiResult.message) obj;

        if (hasMethod() != other.hasMethod()) return false;
        if (hasMethod()) {
          if (!getMethod()
              .equals(other.getMethod())) return false;
        }
        if (hasPayload() != other.hasPayload()) return false;
        if (hasPayload()) {
          if (!getPayload()
              .equals(other.getPayload())) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasMethod()) {
          hash = (37 * hash) + METHOD_FIELD_NUMBER;
          hash = (53 * hash) + getMethod().hashCode();
        }
        if (hasPayload()) {
          hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
          hash = (53 * hash) + getPayload().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static ProtoApiResultOuterClass.ProtoApiResult.message parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoApiResultOuterClass.ProtoApiResult.message parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoApiResultOuterClass.ProtoApiResult.message parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoApiResultOuterClass.ProtoApiResult.message parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoApiResultOuterClass.ProtoApiResult.message parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ProtoApiResultOuterClass.ProtoApiResult.message parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ProtoApiResultOuterClass.ProtoApiResult.message parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoApiResultOuterClass.ProtoApiResult.message parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoApiResultOuterClass.ProtoApiResult.message parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static ProtoApiResultOuterClass.ProtoApiResult.message parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static ProtoApiResultOuterClass.ProtoApiResult.message parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static ProtoApiResultOuterClass.ProtoApiResult.message parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(ProtoApiResultOuterClass.ProtoApiResult.message prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ProtoApiResult.message}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ProtoApiResult.message)
          ProtoApiResultOuterClass.ProtoApiResult.messageOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ProtoApiResultOuterClass.internal_static_ProtoApiResult_message_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ProtoApiResultOuterClass.internal_static_ProtoApiResult_message_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ProtoApiResultOuterClass.ProtoApiResult.message.class, ProtoApiResultOuterClass.ProtoApiResult.message.Builder.class);
        }

        // Construct using ProtoApiResultOuterClass.ProtoApiResult.message.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          method_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          payload_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ProtoApiResultOuterClass.internal_static_ProtoApiResult_message_descriptor;
        }

        @java.lang.Override
        public ProtoApiResultOuterClass.ProtoApiResult.message getDefaultInstanceForType() {
          return ProtoApiResultOuterClass.ProtoApiResult.message.getDefaultInstance();
        }

        @java.lang.Override
        public ProtoApiResultOuterClass.ProtoApiResult.message build() {
          ProtoApiResultOuterClass.ProtoApiResult.message result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public ProtoApiResultOuterClass.ProtoApiResult.message buildPartial() {
          ProtoApiResultOuterClass.ProtoApiResult.message result = new ProtoApiResultOuterClass.ProtoApiResult.message(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.method_ = method_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            to_bitField0_ |= 0x00000002;
          }
          result.payload_ = payload_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ProtoApiResultOuterClass.ProtoApiResult.message) {
            return mergeFrom((ProtoApiResultOuterClass.ProtoApiResult.message)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ProtoApiResultOuterClass.ProtoApiResult.message other) {
          if (other == ProtoApiResultOuterClass.ProtoApiResult.message.getDefaultInstance()) return this;
          if (other.hasMethod()) {
            bitField0_ |= 0x00000001;
            method_ = other.method_;
            onChanged();
          }
          if (other.hasPayload()) {
            setPayload(other.getPayload());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ProtoApiResultOuterClass.ProtoApiResult.message parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ProtoApiResultOuterClass.ProtoApiResult.message) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object method_ = "";
        /**
         * <code>optional string method = 1;</code>
         * @return Whether the method field is set.
         */
        public boolean hasMethod() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional string method = 1;</code>
         * @return The method.
         */
        public java.lang.String getMethod() {
          java.lang.Object ref = method_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              method_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string method = 1;</code>
         * @return The bytes for method.
         */
        public com.google.protobuf.ByteString
            getMethodBytes() {
          java.lang.Object ref = method_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            method_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string method = 1;</code>
         * @param value The method to set.
         * @return This builder for chaining.
         */
        public Builder setMethod(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          method_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string method = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearMethod() {
          bitField0_ = (bitField0_ & ~0x00000001);
          method_ = getDefaultInstance().getMethod();
          onChanged();
          return this;
        }
        /**
         * <code>optional string method = 1;</code>
         * @param value The bytes for method to set.
         * @return This builder for chaining.
         */
        public Builder setMethodBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          method_ = value;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes payload = 2;</code>
         * @return Whether the payload field is set.
         */
        @java.lang.Override
        public boolean hasPayload() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional bytes payload = 2;</code>
         * @return The payload.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getPayload() {
          return payload_;
        }
        /**
         * <code>optional bytes payload = 2;</code>
         * @param value The payload to set.
         * @return This builder for chaining.
         */
        public Builder setPayload(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          payload_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes payload = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearPayload() {
          bitField0_ = (bitField0_ & ~0x00000002);
          payload_ = getDefaultInstance().getPayload();
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:ProtoApiResult.message)
      }

      // @@protoc_insertion_point(class_scope:ProtoApiResult.message)
      private static final ProtoApiResultOuterClass.ProtoApiResult.message DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new ProtoApiResultOuterClass.ProtoApiResult.message();
      }

      public static ProtoApiResultOuterClass.ProtoApiResult.message getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated public static final com.google.protobuf.Parser<message>
          PARSER = new com.google.protobuf.AbstractParser<message>() {
        @java.lang.Override
        public message parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new message(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<message> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<message> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public ProtoApiResultOuterClass.ProtoApiResult.message getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int MESSAGES_FIELD_NUMBER = 1;
    private java.util.List<ProtoApiResultOuterClass.ProtoApiResult.message> messages_;
    /**
     * <code>repeated .ProtoApiResult.message messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<ProtoApiResultOuterClass.ProtoApiResult.message> getMessagesList() {
      return messages_;
    }
    /**
     * <code>repeated .ProtoApiResult.message messages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends ProtoApiResultOuterClass.ProtoApiResult.messageOrBuilder> 
        getMessagesOrBuilderList() {
      return messages_;
    }
    /**
     * <code>repeated .ProtoApiResult.message messages = 1;</code>
     */
    @java.lang.Override
    public int getMessagesCount() {
      return messages_.size();
    }
    /**
     * <code>repeated .ProtoApiResult.message messages = 1;</code>
     */
    @java.lang.Override
    public ProtoApiResultOuterClass.ProtoApiResult.message getMessages(int index) {
      return messages_.get(index);
    }
    /**
     * <code>repeated .ProtoApiResult.message messages = 1;</code>
     */
    @java.lang.Override
    public ProtoApiResultOuterClass.ProtoApiResult.messageOrBuilder getMessagesOrBuilder(
        int index) {
      return messages_.get(index);
    }

    public static final int CURSOR_FIELD_NUMBER = 2;
    private volatile java.lang.Object cursor_;
    /**
     * <code>optional string cursor = 2;</code>
     * @return Whether the cursor field is set.
     */
    @java.lang.Override
    public boolean hasCursor() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string cursor = 2;</code>
     * @return The cursor.
     */
    @java.lang.Override
    public java.lang.String getCursor() {
      java.lang.Object ref = cursor_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cursor_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cursor = 2;</code>
     * @return The bytes for cursor.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCursorBytes() {
      java.lang.Object ref = cursor_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cursor_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FETCH_INTERVAL_FIELD_NUMBER = 3;
    private int fetchInterval_;
    /**
     * <code>optional int32 fetch_interval = 3;</code>
     * @return Whether the fetchInterval field is set.
     */
    @java.lang.Override
    public boolean hasFetchInterval() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional int32 fetch_interval = 3;</code>
     * @return The fetchInterval.
     */
    @java.lang.Override
    public int getFetchInterval() {
      return fetchInterval_;
    }

    public static final int NOW_FIELD_NUMBER = 4;
    private long now_;
    /**
     * <code>optional uint64 now = 4;</code>
     * @return Whether the now field is set.
     */
    @java.lang.Override
    public boolean hasNow() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional uint64 now = 4;</code>
     * @return The now.
     */
    @java.lang.Override
    public long getNow() {
      return now_;
    }

    public static final int INTERNAL_EXT_FIELD_NUMBER = 5;
    private volatile java.lang.Object internalExt_;
    /**
     * <code>optional string internal_ext = 5;</code>
     * @return Whether the internalExt field is set.
     */
    @java.lang.Override
    public boolean hasInternalExt() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string internal_ext = 5;</code>
     * @return The internalExt.
     */
    @java.lang.Override
    public java.lang.String getInternalExt() {
      java.lang.Object ref = internalExt_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          internalExt_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string internal_ext = 5;</code>
     * @return The bytes for internalExt.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getInternalExtBytes() {
      java.lang.Object ref = internalExt_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        internalExt_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < messages_.size(); i++) {
        output.writeMessage(1, messages_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cursor_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(3, fetchInterval_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt64(4, now_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, internalExt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < messages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, messages_.get(i));
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cursor_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, fetchInterval_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, now_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, internalExt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProtoApiResultOuterClass.ProtoApiResult)) {
        return super.equals(obj);
      }
      ProtoApiResultOuterClass.ProtoApiResult other = (ProtoApiResultOuterClass.ProtoApiResult) obj;

      if (!getMessagesList()
          .equals(other.getMessagesList())) return false;
      if (hasCursor() != other.hasCursor()) return false;
      if (hasCursor()) {
        if (!getCursor()
            .equals(other.getCursor())) return false;
      }
      if (hasFetchInterval() != other.hasFetchInterval()) return false;
      if (hasFetchInterval()) {
        if (getFetchInterval()
            != other.getFetchInterval()) return false;
      }
      if (hasNow() != other.hasNow()) return false;
      if (hasNow()) {
        if (getNow()
            != other.getNow()) return false;
      }
      if (hasInternalExt() != other.hasInternalExt()) return false;
      if (hasInternalExt()) {
        if (!getInternalExt()
            .equals(other.getInternalExt())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMessagesCount() > 0) {
        hash = (37 * hash) + MESSAGES_FIELD_NUMBER;
        hash = (53 * hash) + getMessagesList().hashCode();
      }
      if (hasCursor()) {
        hash = (37 * hash) + CURSOR_FIELD_NUMBER;
        hash = (53 * hash) + getCursor().hashCode();
      }
      if (hasFetchInterval()) {
        hash = (37 * hash) + FETCH_INTERVAL_FIELD_NUMBER;
        hash = (53 * hash) + getFetchInterval();
      }
      if (hasNow()) {
        hash = (37 * hash) + NOW_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getNow());
      }
      if (hasInternalExt()) {
        hash = (37 * hash) + INTERNAL_EXT_FIELD_NUMBER;
        hash = (53 * hash) + getInternalExt().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProtoApiResultOuterClass.ProtoApiResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoApiResultOuterClass.ProtoApiResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoApiResultOuterClass.ProtoApiResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoApiResultOuterClass.ProtoApiResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoApiResultOuterClass.ProtoApiResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProtoApiResultOuterClass.ProtoApiResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProtoApiResultOuterClass.ProtoApiResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoApiResultOuterClass.ProtoApiResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoApiResultOuterClass.ProtoApiResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProtoApiResultOuterClass.ProtoApiResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProtoApiResultOuterClass.ProtoApiResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProtoApiResultOuterClass.ProtoApiResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProtoApiResultOuterClass.ProtoApiResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ProtoApiResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ProtoApiResult)
        ProtoApiResultOuterClass.ProtoApiResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProtoApiResultOuterClass.internal_static_ProtoApiResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProtoApiResultOuterClass.internal_static_ProtoApiResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProtoApiResultOuterClass.ProtoApiResult.class, ProtoApiResultOuterClass.ProtoApiResult.Builder.class);
      }

      // Construct using ProtoApiResultOuterClass.ProtoApiResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMessagesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          messagesBuilder_.clear();
        }
        cursor_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        fetchInterval_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        now_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        internalExt_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProtoApiResultOuterClass.internal_static_ProtoApiResult_descriptor;
      }

      @java.lang.Override
      public ProtoApiResultOuterClass.ProtoApiResult getDefaultInstanceForType() {
        return ProtoApiResultOuterClass.ProtoApiResult.getDefaultInstance();
      }

      @java.lang.Override
      public ProtoApiResultOuterClass.ProtoApiResult build() {
        ProtoApiResultOuterClass.ProtoApiResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ProtoApiResultOuterClass.ProtoApiResult buildPartial() {
        ProtoApiResultOuterClass.ProtoApiResult result = new ProtoApiResultOuterClass.ProtoApiResult(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (messagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            messages_ = java.util.Collections.unmodifiableList(messages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.messages_ = messages_;
        } else {
          result.messages_ = messagesBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cursor_ = cursor_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.fetchInterval_ = fetchInterval_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.now_ = now_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.internalExt_ = internalExt_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProtoApiResultOuterClass.ProtoApiResult) {
          return mergeFrom((ProtoApiResultOuterClass.ProtoApiResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProtoApiResultOuterClass.ProtoApiResult other) {
        if (other == ProtoApiResultOuterClass.ProtoApiResult.getDefaultInstance()) return this;
        if (messagesBuilder_ == null) {
          if (!other.messages_.isEmpty()) {
            if (messages_.isEmpty()) {
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMessagesIsMutable();
              messages_.addAll(other.messages_);
            }
            onChanged();
          }
        } else {
          if (!other.messages_.isEmpty()) {
            if (messagesBuilder_.isEmpty()) {
              messagesBuilder_.dispose();
              messagesBuilder_ = null;
              messages_ = other.messages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              messagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMessagesFieldBuilder() : null;
            } else {
              messagesBuilder_.addAllMessages(other.messages_);
            }
          }
        }
        if (other.hasCursor()) {
          bitField0_ |= 0x00000002;
          cursor_ = other.cursor_;
          onChanged();
        }
        if (other.hasFetchInterval()) {
          setFetchInterval(other.getFetchInterval());
        }
        if (other.hasNow()) {
          setNow(other.getNow());
        }
        if (other.hasInternalExt()) {
          bitField0_ |= 0x00000010;
          internalExt_ = other.internalExt_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProtoApiResultOuterClass.ProtoApiResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProtoApiResultOuterClass.ProtoApiResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ProtoApiResultOuterClass.ProtoApiResult.message> messages_ =
        java.util.Collections.emptyList();
      private void ensureMessagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          messages_ = new java.util.ArrayList<ProtoApiResultOuterClass.ProtoApiResult.message>(messages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoApiResultOuterClass.ProtoApiResult.message, ProtoApiResultOuterClass.ProtoApiResult.message.Builder, ProtoApiResultOuterClass.ProtoApiResult.messageOrBuilder> messagesBuilder_;

      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public java.util.List<ProtoApiResultOuterClass.ProtoApiResult.message> getMessagesList() {
        if (messagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(messages_);
        } else {
          return messagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public int getMessagesCount() {
        if (messagesBuilder_ == null) {
          return messages_.size();
        } else {
          return messagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public ProtoApiResultOuterClass.ProtoApiResult.message getMessages(int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);
        } else {
          return messagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public Builder setMessages(
          int index, ProtoApiResultOuterClass.ProtoApiResult.message value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.set(index, value);
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public Builder setMessages(
          int index, ProtoApiResultOuterClass.ProtoApiResult.message.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.set(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public Builder addMessages(ProtoApiResultOuterClass.ProtoApiResult.message value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public Builder addMessages(
          int index, ProtoApiResultOuterClass.ProtoApiResult.message value) {
        if (messagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMessagesIsMutable();
          messages_.add(index, value);
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public Builder addMessages(
          ProtoApiResultOuterClass.ProtoApiResult.message.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public Builder addMessages(
          int index, ProtoApiResultOuterClass.ProtoApiResult.message.Builder builderForValue) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.add(index, builderForValue.build());
          onChanged();
        } else {
          messagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public Builder addAllMessages(
          java.lang.Iterable<? extends ProtoApiResultOuterClass.ProtoApiResult.message> values) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, messages_);
          onChanged();
        } else {
          messagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public Builder clearMessages() {
        if (messagesBuilder_ == null) {
          messages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          messagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public Builder removeMessages(int index) {
        if (messagesBuilder_ == null) {
          ensureMessagesIsMutable();
          messages_.remove(index);
          onChanged();
        } else {
          messagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public ProtoApiResultOuterClass.ProtoApiResult.message.Builder getMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public ProtoApiResultOuterClass.ProtoApiResult.messageOrBuilder getMessagesOrBuilder(
          int index) {
        if (messagesBuilder_ == null) {
          return messages_.get(index);  } else {
          return messagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public java.util.List<? extends ProtoApiResultOuterClass.ProtoApiResult.messageOrBuilder> 
           getMessagesOrBuilderList() {
        if (messagesBuilder_ != null) {
          return messagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(messages_);
        }
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public ProtoApiResultOuterClass.ProtoApiResult.message.Builder addMessagesBuilder() {
        return getMessagesFieldBuilder().addBuilder(
            ProtoApiResultOuterClass.ProtoApiResult.message.getDefaultInstance());
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public ProtoApiResultOuterClass.ProtoApiResult.message.Builder addMessagesBuilder(
          int index) {
        return getMessagesFieldBuilder().addBuilder(
            index, ProtoApiResultOuterClass.ProtoApiResult.message.getDefaultInstance());
      }
      /**
       * <code>repeated .ProtoApiResult.message messages = 1;</code>
       */
      public java.util.List<ProtoApiResultOuterClass.ProtoApiResult.message.Builder> 
           getMessagesBuilderList() {
        return getMessagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProtoApiResultOuterClass.ProtoApiResult.message, ProtoApiResultOuterClass.ProtoApiResult.message.Builder, ProtoApiResultOuterClass.ProtoApiResult.messageOrBuilder> 
          getMessagesFieldBuilder() {
        if (messagesBuilder_ == null) {
          messagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProtoApiResultOuterClass.ProtoApiResult.message, ProtoApiResultOuterClass.ProtoApiResult.message.Builder, ProtoApiResultOuterClass.ProtoApiResult.messageOrBuilder>(
                  messages_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          messages_ = null;
        }
        return messagesBuilder_;
      }

      private java.lang.Object cursor_ = "";
      /**
       * <code>optional string cursor = 2;</code>
       * @return Whether the cursor field is set.
       */
      public boolean hasCursor() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string cursor = 2;</code>
       * @return The cursor.
       */
      public java.lang.String getCursor() {
        java.lang.Object ref = cursor_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cursor_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cursor = 2;</code>
       * @return The bytes for cursor.
       */
      public com.google.protobuf.ByteString
          getCursorBytes() {
        java.lang.Object ref = cursor_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cursor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cursor = 2;</code>
       * @param value The cursor to set.
       * @return This builder for chaining.
       */
      public Builder setCursor(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cursor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cursor = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCursor() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cursor_ = getDefaultInstance().getCursor();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cursor = 2;</code>
       * @param value The bytes for cursor to set.
       * @return This builder for chaining.
       */
      public Builder setCursorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cursor_ = value;
        onChanged();
        return this;
      }

      private int fetchInterval_ ;
      /**
       * <code>optional int32 fetch_interval = 3;</code>
       * @return Whether the fetchInterval field is set.
       */
      @java.lang.Override
      public boolean hasFetchInterval() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 fetch_interval = 3;</code>
       * @return The fetchInterval.
       */
      @java.lang.Override
      public int getFetchInterval() {
        return fetchInterval_;
      }
      /**
       * <code>optional int32 fetch_interval = 3;</code>
       * @param value The fetchInterval to set.
       * @return This builder for chaining.
       */
      public Builder setFetchInterval(int value) {
        bitField0_ |= 0x00000004;
        fetchInterval_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 fetch_interval = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearFetchInterval() {
        bitField0_ = (bitField0_ & ~0x00000004);
        fetchInterval_ = 0;
        onChanged();
        return this;
      }

      private long now_ ;
      /**
       * <code>optional uint64 now = 4;</code>
       * @return Whether the now field is set.
       */
      @java.lang.Override
      public boolean hasNow() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional uint64 now = 4;</code>
       * @return The now.
       */
      @java.lang.Override
      public long getNow() {
        return now_;
      }
      /**
       * <code>optional uint64 now = 4;</code>
       * @param value The now to set.
       * @return This builder for chaining.
       */
      public Builder setNow(long value) {
        bitField0_ |= 0x00000008;
        now_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 now = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNow() {
        bitField0_ = (bitField0_ & ~0x00000008);
        now_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object internalExt_ = "";
      /**
       * <code>optional string internal_ext = 5;</code>
       * @return Whether the internalExt field is set.
       */
      public boolean hasInternalExt() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string internal_ext = 5;</code>
       * @return The internalExt.
       */
      public java.lang.String getInternalExt() {
        java.lang.Object ref = internalExt_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            internalExt_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string internal_ext = 5;</code>
       * @return The bytes for internalExt.
       */
      public com.google.protobuf.ByteString
          getInternalExtBytes() {
        java.lang.Object ref = internalExt_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          internalExt_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string internal_ext = 5;</code>
       * @param value The internalExt to set.
       * @return This builder for chaining.
       */
      public Builder setInternalExt(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        internalExt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string internal_ext = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearInternalExt() {
        bitField0_ = (bitField0_ & ~0x00000010);
        internalExt_ = getDefaultInstance().getInternalExt();
        onChanged();
        return this;
      }
      /**
       * <code>optional string internal_ext = 5;</code>
       * @param value The bytes for internalExt to set.
       * @return This builder for chaining.
       */
      public Builder setInternalExtBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        internalExt_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ProtoApiResult)
    }

    // @@protoc_insertion_point(class_scope:ProtoApiResult)
    private static final ProtoApiResultOuterClass.ProtoApiResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProtoApiResultOuterClass.ProtoApiResult();
    }

    public static ProtoApiResultOuterClass.ProtoApiResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProtoApiResult>
        PARSER = new com.google.protobuf.AbstractParser<ProtoApiResult>() {
      @java.lang.Override
      public ProtoApiResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoApiResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProtoApiResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoApiResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ProtoApiResultOuterClass.ProtoApiResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoApiResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoApiResult_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProtoApiResult_message_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProtoApiResult_message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ProtoApiResult.proto\"\262\001\n\016ProtoApiResul" +
      "t\022)\n\010messages\030\001 \003(\0132\027.ProtoApiResult.mes" +
      "sage\022\016\n\006cursor\030\002 \001(\t\022\026\n\016fetch_interval\030\003" +
      " \001(\005\022\013\n\003now\030\004 \001(\004\022\024\n\014internal_ext\030\005 \001(\t\032" +
      "*\n\007message\022\016\n\006method\030\001 \001(\t\022\017\n\007payload\030\002 " +
      "\001(\014"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProtoApiResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProtoApiResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoApiResult_descriptor,
        new java.lang.String[] { "Messages", "Cursor", "FetchInterval", "Now", "InternalExt", });
    internal_static_ProtoApiResult_message_descriptor =
      internal_static_ProtoApiResult_descriptor.getNestedTypes().get(0);
    internal_static_ProtoApiResult_message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProtoApiResult_message_descriptor,
        new java.lang.String[] { "Method", "Payload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
